

CREATE TABLE "catalogue" (
	`BOOK_NAME`	    VARCHAR(50) NOT NULL,
	`URL`	        VARCHAR(100) NOT NULL UNIQUE,
	`CHAPTER`	    VARCHAR(50),
	`STATUS`	    INT,
	`CREATETIME`	DATETIME,
	`UPDATATIME`	DATETIME,
	`id`	        INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE
);


CREATE TABLE "book_info" (
	`id`	        INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`BOOK_ID`       VARCHAR(50) NOT NULL UNIQUE,
	`NAME`	        VARCHAR(50) NOT NULL UNIQUE,
	`AUTHOR`	    VARCHAR(50) NOT NULL,
	`BOOK_TYPE`	    VARCHAR(100),
	`STATUS`	    VARCHAR(50),
	`CREATETIME`	DATETIME,
	`UPDATATIME`	DATETIME
);


CREATE TABLE "context_info" (
	`id`	            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`BOOK_NAME`	        VARCHAR(50) NOT NULL,
	`CHAPTER_NAME`	    VARCHAR(200) NOT NULL UNIQUE,
	`CONTEXT`	        TEXT NOT NULL,
	`CREATETIME`	    DATETIME,
	`UPDATATIME`	    DATETIME
);

CREATE TABLE "context_info" (
	`id`	            INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`BOOK_ID`           VARCHAR(50) NOT NULL UNIQUE,
	`BOOK_NAME`	        VARCHAR(50) NOT NULL,
	`CHAPTER_NAME`	    VARCHAR(200) NOT NULL UNIQUE,
	`CONTEXT_PATH`	    TEXT NOT NULL,
	`CREATETIME`	    DATETIME,
	`UPDATATIME`	    DATETIME
);

delete from catalogue;
delete from context_info;
delete from 斗破苍穹_context;
